//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyDetails
    {
        public int Id { get; set; }
        public string company_name { get; set; }
        public string email { get; set; }
        public string TaxPIN { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Logo { get; set; }
        public string Country { get; set; }
        public string swypecode { get; set; }
        public string Adminpin { get; set; }
        public Nullable<int> Cashlesslimit { get; set; }
    }
}
