//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPOS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Database1.mdf" +
            ";Integrated Security=True;Connect Timeout=30")]
        public string Database1ConnectionString {
            get {
                return ((string)(this["Database1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Database1.mdf" +
            ";Integrated Security=True;Connect Timeout=30")]
        public string C__USERS_PUBLIC_DOCUMENTS_NEWPOS_BIN_DEBUG_DATABASE1_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_PUBLIC_DOCUMENTS_NEWPOS_BIN_DEBUG_DATABASE1_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=\"C:\\USERS\\G4\\DOCUMENTS\\VISUAL " +
            "STUDIO 2015\\PROJECTS\\NEWPOS\\BIN\\DEBUG\\DATABASE1.MDF\";Integrated Security=True;Co" +
            "nnect Timeout=30;Encrypt=False;TrustServerCertificate=True")]
        public string C__USERS_G4_DOCUMENTS_VISUAL_STUDIO_2015_PROJECTS_NEWPOS_BIN_DEBUG_DATABASE1_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_G4_DOCUMENTS_VISUAL_STUDIO_2015_PROJECTS_NEWPOS_BIN_DEBUG_DATABASE1_MDFC" +
                    "onnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://swypepay.co.ke/sandbox/frontend/web/index.php?r=user-profile/login-user")]
        public string loginuserapi {
            get {
                return ((string)(this["loginuserapi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://swypepay.co.ke/sandbox/frontend/web/index.php?r=user-profile/check-card-ba" +
            "lance-without-password")]
        public string checkcardbalancewopassword {
            get {
                return ((string)(this["checkcardbalancewopassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://swypepay.co.ke/sandbox/frontend/web/index.php?r=user-profile/check-out-wit" +
            "hout-password")]
        public string checkoutwopassword {
            get {
                return ((string)(this["checkoutwopassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://swypepay.co.ke/sandbox/frontend/web/index.php?r=user-profile/card-check-ou" +
            "t")]
        public string cardcheckout {
            get {
                return ((string)(this["cardcheckout"]));
            }
        }
    }
}
